# Introduction to Jupyter and Python
This is a [Jupyter](https://jupyter.org/) notebook.
[Here is a Jupyter tutorial](https://youtu.be/Rc4JQWowG5I).

This _cell_ is a [Markdown](http://daringfireball.net/projects/markdown/syntax) cell: it contains text with markup commands rather than executable computer code.

You can also style text in a Markdown cell using <strong>html</strong> <em>tags</em>.

Markdown cells in Jupyter support [MathJax](https://www.mathjax.org/), so you can write lovely typeset mathematics, e.g., $ e^{i\pi} = -1$.

$$
  e^x \equiv \sum_{j=1}^\infty \frac{x^j}{j!}.
$$

Here is a [demo of Markdown and MathJax in Jupyter](https://youtu.be/-F4WS8o-G2A)

This particular Jupyter notebook is a Python notebook (there are also R and Julia notebooks, among other programming languages).
This notebook is communicating with a Python kernel and can execute Python commands.

[Here is an introduction to Python](https://www.python.org/about/gettingstarted/). 

For a more thorough introduction to Python for Science, see https://scipy-lectures.github.io/


## Jupyter

Most of Jupyter's functionality is clear from its drop-down menus: commands to insert or delete cells, to execute cells, to clear output, etc.

One of the most useful features of Jupyter is its help functions and tab completion.

For instance, typing "tab" while you are typing the name of a function will give you a list of functions that start with the letters you have typed so far.

Please click "help" and take the User Interface Tour.


## Python

The rest of this notebook is a brief introduction to Python (within Jupyter). 
We will see more of Python in later sections of the course, as we encounter particular topics linear algebra, least squares, optimization, random number generation, the Bootstrap, etc.

In [1]:
# This is a code cell (but this line is a comment, because it starts with '#')
# This is a Python notebook, so you can type Python commands into this cell, for example:
print('Hello world!')

Hello world!


In [2]:
# more Python

# arithmetic
print 5+2 
print 5^2
print 5/2 # by default, division of integers is truncated.
print 5/2.0

7
7
2
2.5


In [3]:
# You will use many Python packages to get higher-level data constructs, functions, etc.
#  __future__ arithmetic doesn't truncate integer division
from __future__ import division
print 5/2

2.5


In [4]:
sqrt(4)  # sqrt is not in the core language. It's in the math package.

NameError: name 'sqrt' is not defined

In [5]:
import math
print math.sqrt(4)
print math.sqrt(-1)  # no complex arithmetic in the basic math package

2.0


ValueError: math domain error

In [20]:
import numpy as np  # numeric Python. Lots of goodies.
import scipy as sp  # scientific Python. More goodies.

print np.sqrt(-1+0j)      # Python uses j to denote sqrt(-1). Numpy can take the square root of complex numbers
print np.sqrt(4)
print np.sqrt(4+0j)

1j
2.0
(2+0j)


In [7]:
# variables
x = 5
print x
print x**2
y = x
print y

5
25
5


In [8]:
# Python has some pre-defined values
print math.pi
print math.e

3.14159265359
2.71828182846


In [9]:
# not a number
x = float('nan')
print x
print x + 1  # arithmetic with "NA" gives "NA"

print math.isnan(x)
print math.isnan(math.pi)

nan
nan
True
False


In [13]:
# ranges
print range(5) # by default, ranges start at 0
print range(1,5) # includes lower endpoint but not upper endpoint
print range(1,10,2) # step size
print range(10,5,-1) # negative steps are OK 

[0, 1, 2, 3, 4]
[1, 2, 3, 4]
[1, 3, 5, 7, 9]
[10, 9, 8, 7, 6]


In [16]:
# non-integer spaced ranges
print np.linspace(1, 3, num=5)  # 5 equispaced points between 1 and 3
print np.linspace(3, 1, num=5)  # 5 equispaced points between 3 and 1

print np.arange(1, 2, step = 0.1) # go from 1 to 2 in steps of 0.1
print np.arange(3, 1, step = -0.5) # from 3 to 1 in steps of -0.5


[ 1.   1.5  2.   2.5  3. ]
[ 3.   2.5  2.   1.5  1. ]
[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9]
[ 3.   2.5  2.   1.5]


In [ ]:
# how long is a list?
y = range(5)
print len(y)  

# indexing a list
print y[0]  # Python uses 0-based indexing
print y[4]
print y[6]  # nothing there!

In [ ]:
# you can append to lists
y.append(2)
print y
print len(y)

In [17]:
# you can pop elements from lists
y = range(5)
print y
print y.pop()  # remove and return the last element of the list
print y  # last element is gone now

y = range(5)
print y
print y.pop(1) # remove and return the element in position 1 (recall Python uses 0-based indices)
print y  # element in position 1 is gone now

[0, 1, 2, 3, 4]
4
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
1
[0, 2, 3, 4]


In [ ]:
# slightly more advanced indexing
#
y = range(5)
print y[2:4] # 3rd and 4th elements of y--remember, last element isn't included
print y[2:5] # 3rd through 5th

# logical indexing: easy to use list comprehensions
ygt2 = [v for v in y if v > 2]
print ygt2

# alternatively, use a numpy array
y = np.array(range(5))
print y[np.where(y > 2)]

In [ ]:
# build a matrix
x = np.array([[0,1], [0,2], [1,3]])
print x
print x.T

In [ ]:
# building arrays
x = np.array(range(1,6))
y = np.array(range(6, 11))

# row binding
print np.vstack((x,y))  # glue these together as rows
print np.vstack((x,y,x**2))

# column binding
print np.vstack((x,y)).T  # glue these together as columns
print np.vstack((x,y,x**2)).T

In [ ]:
# pre-defined arrays in numpy
print np.ones((3,4))
print np.zeros((4,3))

In [ ]:
# changing the dimension of an array
x = np.ones((3,4))
print x
x = np.reshape(x, (4,3))
print x

In [ ]:
# operations on numpy arrays
y = np.array(range(1,5))
print y
print y**2
print y^2  # careful: the caret operator is bitwise XOR, not exponentiation!
print np.sqrt(y)
print np.log(y)

In [23]:
# linear algebra
x = np.array([[0,1], [0,2], [1,3]])
print x
xtx = np.dot(x.T, x) # matrix multiplication
print xtx

from scipy import linalg

xtxInv = sp.linalg.inv(xtx)  # matrix inversion is in the linalg part of scipy. 
                             # NOTE: generally should avoid inverting matrices
                             # there are much better ways to solve linear systems

print xtxInv

print np.dot(xtx, xtxInv)  # was that really the inverse?

[[0 1]
 [0 2]
 [1 3]]
[[ 1  3]
 [ 3 14]]
[[ 2.8 -0.6]
 [-0.6  0.2]]
[[  1.00000000e+00  -1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]


In [25]:
# solving linear systems

b = np.array([0, 1])
y = linalg.solve(xtx,b) 
print y, np.dot(xtx,y) -b

[-0.6  0.2] [ 0.  0.]


In [26]:
# logical (Boolean) variables
print True
print False
x = True
print x
print 1 == 2
print 1 > 2
print 1 >= 2
print 1 != 2

True
False
True
False
False
False
True


In [27]:
# logical operators
print not True
print not False
print True or False  # logical "or"
print False or False
print True and True  # logical "and"
print True and False
print not(True and False)

False
True
True
False
True
False
True


In [28]:
# most numerical values can be cast as Booleans
print 0 and True
print 0 or True
print 1 and True
print math.pi and True
print "hello" and True 

0
True
True
True
True


In [29]:
# sorting, max, min
x = np.array(range(10,5,-1))
print x
print np.sort(x)
# what permutation puts the list in sorted order?
print np.argsort(x)
#
print np.max(x), np.min(x), np.max(x**2), np.max(x)**2
print np.sum(x), np.cumsum(x)
print np.prod(x), np.cumprod(x)

[10  9  8  7  6]
[ 6  7  8  9 10]
[4 3 2 1 0]
10 6 100 100
40 [10 19 27 34 40]
30240 [   10    90   720  5040 30240]


In [30]:
# Set operations
x = [1, 2, 3, 3, 3]
print x
s = set(x)
print s
print len(s) # cardinality of s

print 1 in s  # is 1 an element of s?
print 0 not in s  #

print s.isdisjoint([1, 2])
print s.isdisjoint([0, 10])

print s.issubset(range(1,5))
print s <= range(1,5)
print s.issubset(range(2))
print s <= range(2)

print s < range(1,5)  # proper subset?
print s < range(1,4)

print s.issuperset(range(1,3))
print s >= range(1,3)
print s > range(1,4)
print s > range(1,3)

print s.union(range(5,10))
print s | set(range(5,10))

print s.intersection(range(2))
print s & set(range(2))

print s.difference(range(2))

[1, 2, 3, 3, 3]
set([1, 2, 3])
3
True
True
False
True
True
False
False
False
False
False
True
True
True
True
set([1, 2, 3, 5, 6, 7, 8, 9])
set([1, 2, 3, 5, 6, 7, 8, 9])
set([1])
set([1])
set([2, 3])


In [31]:
# printing and flow control
x = 3

for i in range(x):  # first flow control
    print x**i

i =1
while i <= 5: # second flow control
    print x**i
    i =i+1

if 1 < 2:  # third flow control
    print '1 is less than 2'


if 2 < 1:
    print '2 is less than 1'
else:
    print '2 is not less than 1'

if 2 < 0:
    print '2 is less than 0'
elif 2 < 1:
    print '2 is less than 1'
else:
    print '2 is neither less than 1 nor less than zero'

1
3
9
3
9
27
81
243
1 is less than 2
2 is not less than 1
2 is neither less than 1 nor less than zero


Next chapter: [Probability](prob.ipynb)